name: Build and Deploy Logic Gates Simulator

on:
   push:
      branches: [master]
   pull_request:
      branches: [master]

jobs:
   build-and-release-jar:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up Java
           uses: actions/setup-java@v2
           with:
              distribution: "temurin"
              java-version: "21"

         - name: Rename JAR file
           run: mv logic_gates-1.0-SNAPSHOT-shaded.jar logic_gate-1.0-SNAPSHOT.jar

         - name: Get Release by Tag
           id: get_release
           uses: octokit/request-action@v2.x
           with:
              route: GET /repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           continue-on-error: true

         - name: Delete Release if Exists
           if: steps.get_release.outputs.status == 200
           uses: octokit/request-action@v2.x
           with:
              route: DELETE /repos/${{ github.repository }}/releases/${{ fromJson(steps.get_release.outputs.data).id }}
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

         - name: Create Release
           id: create_release
           uses: actions/create-release@v1
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
              tag_name: ${{ github.ref_name }}
              release_name: Release ${{ github.ref_name }}
              draft: false
              prerelease: false

         - name: Upload JAR file to Release
           uses: actions/upload-release-asset@v1
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ./logic_gate-1.0-SNAPSHOT.jar
              asset_name: logic_gate-1.0-SNAPSHOT.jar
              asset_content_type: application/java-archive
