name: Generate and Deploy Javadocs

on:
   push:
      branches: [master]
   pull_request:
      branches: [master]
   workflow_dispatch:

jobs:
   build-and-release-javadoc:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up Java
           uses: actions/setup-java@v2
           with:
              distribution: "temurin"
              java-version: "21"

         - name: Build with Maven
           run: mvn clean package

         - name: Generate Javadoc
           run: mvn javadoc:javadoc

         - name: Zip Javadoc
           run: zip -r javadoc.zip target/site/apidocs

         - name: Get Release by Tag
           id: get_release
           uses: octokit/request-action@v2.x
           with:
              route: GET /repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           continue-on-error: true

         - name: Delete Release if Exists
           if: ${{ steps.get_release.outputs.status == 200 }}
           uses: octokit/request-action@v2.x
           with:
              route: DELETE /repos/${{ github.repository }}/releases/${{ fromJson(steps.get_release.outputs.data).id }}
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

         - name: Create Release
           id: create_release
           uses: actions/create-release@v1
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
              tag_name: ${{ github.ref_name }}
              release_name: Release ${{ github.ref_name }}
              draft: false
              prerelease: false

         - name: Upload Javadoc to Release
           uses: actions/upload-release-asset@v1
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ./javadoc.zip
              asset_name: javadoc.zip
              asset_content_type: application/zip
